#ifndef DESC_BOS_H
#define DESC_BOS_H

#include "adapter_includes.h"

enum
{
  VENDOR_REQUEST_WEBUSB = 1,
  VENDOR_REQUEST_MICROSOFT = 2,
  VENDOR_REQUEST_GET_MODE = 3,
  VENDOR_REQUEST_SET_MODE = 4,
  VENDOR_REQUEST_REBOOT_BOOTLOADER = 5,
  VENDOR_REQUEST_GET_MS_OS_DESCRIPTOR = 7,
  VENDOR_REQUEST_GET_BRIGHTNESS = 8,
  VENDOR_REQUEST_SET_BRIGHTNESS = 9,
};

#define ITF_NUM_VENDOR 0

extern uint8_t const desc_bos[];
extern uint8_t const desc_ms_os_20[];

#endif